DELETE http://127.0.0.1:9099/api/entry/1
Content-Type: application/json

{
    "id_usuario": 1,
    "num_conta": 1001,
    "id_categoria": 7,
    "descricao": "Salario Mes Dezembro",
    "valor": 3205.25
}



# POST http://127.0.0.1:9099/api/user
# Content-Type: application/json
# 
# {
#   "nome":"Jeferson", 
#   "email":"jeferson123@gmail.com", 
#   "senha":"1234", 
#   "data_nasc":"1983-01-29" ,
#   "cpf":"12345678910", 
#   "saldo":0.00
# }