GET http://127.0.0.1:9099/api/user/12345678901
Content-Type: application/json

{
    "nome": "João",
    "email": "joao.silva@example.com",
    "senha": "senhaSegura123",
    "data_nasc": "1990-05-15",
    "cpf": "12345678901",
    "saldo": 1500.75
}