POST http://127.0.0.1:9099/api/entry
Content-Type: application/json

  {
      "id_usuario": 1,
      "num_conta": 1001,
      "id_categoria": 7,
      "descricao": "Salario Mes Dezembro",
      "valor": 15800.00
  }


#   {
#     "nome":"Jeferson", 
#     "email":"jeferson123@gmail.com", 
#     "senha":"1234", 
#     "data_nasc":"1983-01-29" ,
#     "cpf":"12345678910", 
#     "saldo":0.00
#   }

#  {
#      "nome": "Comprar um carro",
#      "descricao": "Comprar um carro novo",
#      "valor_alvo": 30000.00,
#      "prazo_final": "2026-12-31"
#  }