DROP DATABASE IF EXISTS finance_manager;
CREATE DATABASE IF NOT EXISTS finance_manager;

USE finance_manager;

DROP TABLE IF EXISTS user;
CREATE TABLE IF NOT EXISTS user(
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(30),
    email VARCHAR(155),
    password VARCHAR(255),
    cpf VARCHAR (11),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

